#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/smgr
#
# IDENTIFICATION
#    src/backend/storage/smgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/zns
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	mkreq.o \

include $(top_srcdir)/src/backend/common.mk
